src/Entity/ManagerProject.php
<?php

namespace App\Entity;

use App\Repository\ManagerProjectRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ManagerProjectRepository::class)]
class ManagerProject
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $start_date_forecast = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $end_date_forecast = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $projectLeader = null;

    #[ORM\OneToMany(mappedBy: 'project', targetEntity: Tasks::class, cascade: ['persist', 'remove'])]
    private Collection $tasks;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(?\DateTimeInterface $start_date): static
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getStartDateForecast(): ?\DateTimeInterface
    {
        return $this->start_date_forecast;
    }

    public function setStartDateForecast(?\DateTimeInterface $start_date_forecast): static
    {
        $this->start_date_forecast = $start_date_forecast;

        return $this;
    }

    public function getEndDateForecast(): ?\DateTimeInterface
    {
        return $this->end_date_forecast;
    }

    public function setEndDateForecast(?\DateTimeInterface $end_date_forecast): static
    {
        $this->end_date_forecast = $end_date_forecast;

        return $this;
    }

    public function getProjectLeader(): ?User
    {
        return $this->projectLeader;
    }
    
    public function setProjectLeader(?User $projectLeader): self
    {
        $this->projectLeader = $projectLeader;
    
        return $this;
    }

    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Tasks $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks->add($task);
            $task->setProject($this);
        }

        return $this;
    }

    public function removeTask(Tasks $task): self
    {
        if ($this->tasks->removeElement($task)) {
            // Définir le projet sur null (s'il est défini)
            if ($task->getProject() === $this) {
                $task->setProject(null);
            }
        }

        return $this;
    }
}

src/Entity/Parameter.php
<?php

namespace App\Entity;

use App\Repository\ParameterRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ParameterRepository::class)]
class Parameter
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 35)]
    #[Assert\NotBlank(message: "Le champ paramKey ne doit pas être vide.")]
    #[Assert\Length(max: 35, maxMessage: "Le paramKey ne doit pas dépasser {{ limit }} caractères.")]
    private ?string $paramKey = null;

    #[ORM\Column(length: 35)]
    #[Assert\NotBlank(message: "Le champ paramValue ne doit pas être vide.")]
    #[Assert\Length(max: 35, maxMessage: "Le paramValue ne doit pas dépasser {{ limit }} caractères.")]
    private ?string $paramValue = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(message: "Le champ paramDateFrom ne doit pas être vide.")]
    private ?\DateTimeInterface $paramDateFrom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\NotBlank(message: "Le champ paramDateTo ne doit pas être vide.")]
    private ?\DateTimeInterface $paramDateTo = null;



    // Getters and Setters
    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;
        return $this;
    }

    public function getParamKey(): ?string
    {
        return $this->paramKey;
    }

    public function setParamKey(string $paramKey): static
    {
        $this->paramKey = $paramKey;
        return $this;
    }

    public function getParamValue(): ?string
    {
        return $this->paramValue;
    }

    public function setParamValue(string $paramValue): static
    {
        $this->paramValue = $paramValue;
        return $this;
    }

    public function getParamDateFrom(): ?\DateTimeInterface
    {
        return $this->paramDateFrom;
    }

    public function setParamDateFrom(\DateTimeInterface $paramDateFrom): static
    {
        $this->paramDateFrom = $paramDateFrom;
        return $this;
    }

    public function getParamDateTo(): ?\DateTimeInterface
    {
        return $this->paramDateTo;
    }

    public function setParamDateTo(\DateTimeInterface $paramDateTo): static
    {
        $this->paramDateTo = $paramDateTo;
        return $this;
    }

}

src/Controller/ParameterController.php
<?php

namespace App\Controller;

use App\Form\EmailUpdateType;
use App\Form\PasswordUpdateType;
use App\Form\SearchFormType;
use App\Form\AppFormParameterType;
use App\Entity\Parameters;
use App\Entity\User;
use App\Entity\Customers;
use App\Entity\ManagerProject;
use App\Entity\Tasks;
use App\Form\CustomerType;
use Symfony\Bundle\SecurityBundle\Security;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Validator\Validator\ValidatorInterface; // Import du bon ValidatorInterface
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Attribute\Route;
use Psr\Log\LoggerInterface;


class ParameterController extends AbstractController
{
    #[Route('/parameter/app_configuration', name: 'app_parameter_app_configuration', methods: ['GET', 'POST'])]
    public function index(Request $request, EntityManagerInterface $entityManager, Security $security): Response
    {   
        // Get current user
        $user = $security->getUser();
        $createForm = $this->createForm(AppFormParameterType::class);
        $searchForm = $this->createForm(SearchFormType::class);

        // $showAll = $searchForm->get('showAll')->getData();
        // $currentDateTime = new \DateTime();
        // // Construire la requête QueryBuilder
        // $parameters = $entityManager->getRepository(Parameter::class)->createQueryBuilder('p');

        // // Filtrer les enregistrements actifs si "showAll" n'est pas coché
        // $parameters->andWhere('p.paramDateFrom <= :currentDate')
        //     ->andWhere('p.paramDateTo >= :currentDate')
        //     ->setParameter('currentDate', $currentDateTime)
        //     ->getQuery()
        //     ->getResult();

        // Récupérer la date actuelle
        $currentDateTime = new \DateTime();
        $parameters = $entityManager->getRepository(Parameters::class)
            ->createQueryBuilder('p')
            ->where('p.paramDateFrom <= :currentDate')
            ->andWhere('p.paramDateTo >= :currentDate')
            ->setParameter('currentDate', $currentDateTime)
            ->getQuery()
            ->getResult();

        return $this->render('parameter/config.html.twig', [
            'searchForm' => $searchForm->createView(), // Passer le formulaire à la vue
            'createForm' => $createForm->createView(),
            'parameters' => $parameters,
            'user' => $user
        ]);
    }
    #[Route('/parameter/search', name: 'app_ajax_search', methods: ['POST'])]
    public function search(Request $request, EntityManagerInterface $entityManager): Response
    {
        // Créer le formulaire
        $form = $this->createForm(SearchFormType::class);
        $form->handleRequest($request);

        // Initialiser la variable des paramètres
        $parameters = [];
        $currentDateTime = new \DateTime();

        // Vérifier si le formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {
            // Récupérer les données du formulaire
            $searchTerm = $form->get('searchTerm')->getData();
            $showAll = $form->get('showAll')->getData();
            $dateSelect = $form->get('dateSelect')->getData();

            // Construire la requête QueryBuilder
            $qb = $entityManager->getRepository(Parameters::class)->createQueryBuilder('p');

            // Appliquer les filtres selon le terme de recherche
            if ($searchTerm) {
                $qb->andWhere('p.paramKey LIKE :searchTerm')
                    ->setParameter('searchTerm', '%' . $searchTerm . '%');
            }

            // Filtrer les enregistrements actifs si "showAll" n'est pas coché
            if (!$showAll) {
                $qb->andWhere('p.paramDateFrom <= :currentDate')
                    ->andWhere('p.paramDateTo >= :currentDate')
                    ->setParameter('currentDate', $currentDateTime);
            }

            // Filtrer par la date sélectionnée si une date est fournie
            if ($dateSelect) {
                $qb->andWhere('p.paramDateFrom <= :dateSelect')
                    ->andWhere('p.paramDateTo >= :dateSelect')
                    ->setParameter('dateSelect', $dateSelect);
            }
            // Exécuter la requête pour obtenir les résultats
            $parameters = $qb->getQuery()->getResult();
        }

        // Générer le HTML avec Twig, même si le tableau est vide
        $html = $this->renderView('parameter/tableau_parameter.html.twig', [
            'parameters' => $parameters,
        ]);

        // Retourner la réponse JSON contenant les résultats et le HTML généré
        return $this->json([
            'parameters' => $parameters, // Retourne les paramètres trouvés
            'html' => $html, // HTML à afficher dans le tableau
        ]);
    }
    #[Route('/parameter/delete/{id}', name: 'app_parameter_delete', methods: ['POST'])]
    public function delete(int $id, EntityManagerInterface $entityManager, Request $request): JsonResponse
    {
        // Récupérer le paramètre à supprimer
        $parameter = $entityManager->getRepository(Parameters::class)->find($id);

        if (!$parameter) {
            return $this->json(['success' => false, 'message' => 'Paramètre non trouvé.'], 404);
        }
        $currentDateTime = new \DateTime();
        if ($parameter->getParamDateTo() < $currentDateTime) {
            return $this->json(['success' => false, 'message' => 'Impossible de supprimer un paramètre non-actif.'], 403);
        }
        $parameter->setParamDateTo($currentDateTime);

        try {
            $entityManager->persist($parameter);
            $entityManager->flush();
        } catch (\Exception $e) {
            return $this->json(['success' => false, 'message' => 'Erreur lors de la mise à jour.'], 500);
        }

        // Récupérer tous les paramètres après la mise à jour
        $allParameters = $entityManager->getRepository(Parameters::class)->findAll();

        // Générer le HTML pour le tableau avec les paramètres restants
        $html = $this->renderView('parameter/tableau_parameter.html.twig', [
            'parameters' => $allParameters,
        ]);

        return $this->json([
            'success' => true,
            'html' => $html, // Retourne le HTML mis à jour
            'parameters' => $allParameters, // Retourne tous les paramètres restants
        ]);
    }
    #[Route('/parameter/create', name: 'app_parameter_create', methods: ['POST'])]
    public function create(Request $request, EntityManagerInterface $entityManager): JsonResponse
    {
        // Créer une nouvelle instance de Parameter
        $parameter = new Parameters();

        // Créer le formulaire et gérer la requête
        $form = $this->createForm(AppFormParameterType::class, $parameter);
        $form->handleRequest($request);

        // Si le formulaire est soumis et valide
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                // Récupérer les valeurs des dates
                $paramDateFrom = $parameter->getParamDateFrom();
                $paramDateTo = $parameter->getParamDateTo();

                // Vérification de la cohérence des dates
                if ($paramDateFrom instanceof \DateTimeInterface && $paramDateTo instanceof \DateTimeInterface) {
                    // Vérifier que la date de début est avant la date de fin
                    if ($paramDateFrom <= $paramDateTo) {
                        // Persister le nouveau paramètre dans la base de données
                        $entityManager->persist($parameter);
                        $entityManager->flush();

                        // Recharger les paramètres mis à jour
                        $parameters = $entityManager->getRepository(Parameters::class)->findAll();

                        // Générer le HTML mis à jour pour le tableau des paramètres
                        $html = $this->renderView('parameter/tableau_parameter.html.twig', [
                            'parameters' => $parameters,
                        ]);

                        // Renvoyer la réponse avec le paramètre créé
                        return $this->json([
                            'success' => true,
                            'parameter' => [
                                'paramKey' => $parameter->getParamKey(),
                                'paramValue' => $parameter->getParamValue(),
                                'paramDateFrom' => $paramDateFrom->format('Y-m-d H:i'), // Formatage des dates
                                'paramDateTo' => $paramDateTo->format('Y-m-d H:i'),
                            ],
                            'html' => $html, // Renvoie le HTML mis à jour
                        ]);
                    } else {
                        // Si la date de début est postérieure à la date de fin
                        return $this->json([
                            'success' => false,
                            'message' => 'La date de début ne peut pas être après la date de fin.',
                        ]);
                    }
                } else {
                    // Si les dates ne sont pas valides
                    return $this->json([
                        'success' => false,
                        'message' => 'Les dates ne sont pas valides.',
                    ]);
                }
            } else {
                // Collecter et retourner les erreurs de validation
                $errors = [];
                foreach ($form->getErrors(true) as $error) {
                    $errors[] = $error->getMessage();
                }

                return $this->json([
                    'success' => false,
                    'message' => 'Formulaire invalide.',

templates/parameter/_menu.html.twig
<div class="parameter_menu">
  <ul class="flex-col">
    <li
      class="{% if app.request.attributes.get('_route') == 'app_parameter_generaux' %}parameter_menu_active{% endif %}"
    >
      <a href="{{ path('app_parameter_generaux') }}">
        <i class="fas fa-cogs" style="margin-right: 8px;"></i>
        Général
      </a>
    </li>
    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_MANAGER') %}
      <li
        class="{% if app.request.attributes.get('_route') == 'app_parameter_users' %}parameter_menu_active{% endif %}"
      >
        <a href="{{ path('app_parameter_users') }}">
          <i class="fas fa-users" style="margin-right: 8px;"></i>
          Gestion Utilisateur
        </a>
      </li>
    {% endif %}
    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_MANAGER') or is_granted('ROLE_LEAD_DEV') or is_granted('ROLE_DEV') %}
      <li
        class="{% if app.request.attributes.get('_route') == 'app_parameter_projects' %}parameter_menu_active{% endif %}"
      >
        <a href="{{ path('app_parameter_projects') }}">
          <i class="fas fa-briefcase" style="margin-right: 8px;"></i>
          Gestion Projets
        </a>
      </li>
    {% endif %}
    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_MANAGER') or is_granted('ROLE_LEAD_DEV') %}
      <li
        class="{% if app.request.attributes.get('_route') == 'app_parameter_customers' %}parameter_menu_active{% endif %}"
      >
        <a href="{{ path('app_parameter_customers') }}">
          <i class="fas fa-user-tie" style="margin-right: 8px;"></i>
          Gestion Client
        </a>
      </li>
    {% endif %}
    <li
      class="{% if app.request.attributes.get('_route') == 'app_parameter_about' %}parameter_menu_active{% endif %}"
    >
      <a href="{{ path('app_parameter_about') }}">
        <i class="fas fa-info-circle" style="margin-right: 8px;"></i>
        À Propos
      </a>
    </li>
  </ul>
</div>

templates/parameter/about.html.twig
{% extends 'base.html.twig' %} 
{% block title %}Digi-3 - À propos{% endblock %}
{% block body %} 

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('styles/parameter/about.css') }}" async>
{% endblock %}

{% include 'includes/header.html.twig' with {'user': user} %}
<section class="parameter_landing flex">
  {% include 'parameter/_menu.html.twig' %}
  <div class="parameter_content need-scrollbar">
    <div class="about-page flex-col">
      <div class="card">
        <h3>Mentions légales</h3>
        <p>
          <strong>Nom de l'entreprise :</strong> <span>Digi-3</span><br />
          <strong>Adresse :</strong> <span>210 avenue de lodève, 34000 Montpellier, France</span><br />
          <strong>Numéro de SIRET :</strong> <span>123 456 789 00010</span><br />
          <strong>Directeur de publication :</strong> <span>Louis Bousquet</span><br />
          <strong>Contact :</strong> <span>contact@digi-3.com</span><br />
          <strong>Hébergeur :</strong> <span>OVH, 2 Rue Kellermann, 59100 Roubaix, France</span>
        </p>
      </div>
      <div class="card">
        <h3>Conditions Générales d'Utilisation (CGU)</h3>
        <p>
          Les conditions générales d'utilisation régissent l'utilisation de l'application Digi-3. En utilisant l'application,
          vous acceptez les conditions. Nous nous réservons le droit de modifier ces conditions à tout moment.
        </p>
        <h4>1. Accès à l'application</h4>
        <p>
          L'accès à l'application Digi-3 est gratuit pour tous les utilisateurs disposant d'un compte.
        </p>
        <h4>2. Propriété intellectuelle</h4>
        <p>
          L'ensemble des contenus disponibles sur l'application sont protégés par le droit d'auteur.
        </p>
        <h4>3. Responsabilité</h4>
        <p>
          Digi-3 décline toute responsabilité en cas de dommage résultant de l'utilisation de l'application.
        </p>
      </div>
      <div class="card">
        <h3>Politique de confidentialité</h3>
        <p>
          Digi-3 s'engage à protéger la vie privée de ses utilisateurs et à respecter la réglementation en vigueur, notamment le RGPD.
        </p>
        <h4>1. Données collectées</h4>
        <p>
          Nous collectons des données personnelles telles que votre nom, adresse e-mail, et préférences d'utilisation.
        </p>
        <h4>2. Utilisation des données</h4>
        <p>
          Les données collectées sont utilisées pour améliorer l'expérience utilisateur et assurer la sécurité des comptes.
        </p>
        <h4>3. Droits des utilisateurs</h4>
        <p>
          Conformément au RGPD, vous disposez d'un droit d'accès, de modification et de suppression de vos données personnelles.
        </p>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/parameter/config.html.twig
{% extends 'base.html.twig' %} 
{% block title %}Digi-3 - Configuration de l'application{% endblock %}
{% block body %}
{% include 'includes/header.html.twig' with {'user': user} %}
<section class="parameter_landing flex">
  {% include 'parameter/_menu.html.twig' %}
  <div class="parameter_content config">
      <h3>Configuration de l'application</h3>
      <div class="searchBar flex">
        {{
          form_start(searchForm, {
            action: path("app_ajax_search"),
            method: "POST",
            attr: { id: "searchForm", class: "flex" }
          })
        }}
        {{ form_widget(searchForm.searchTerm) }}
        <button type="submit" class="flex">
          <img src="/img/search.png" alt="icon rechercher" />
        </button>
        {{ form_widget(searchForm.showAll) }}
        {{ form_end(searchForm) }}
      </div>
      <table class="flex-col">
        <thead>
          <tr class="flex">
            <th>Clée</th>
            <th>Valeur</th>
            <th>DateDebut</th>
            <th>DateFin</th>
          </tr>
        </thead>
        <tbody id="parameter_table" class="flex-col">
          {% include 'parameter/tableau_parameter.html.twig' with { 'parameter':
          parameters } %}
        </tbody>
      </table>
      {{
        form_start(createForm, {
          action: path("app_parameter_create"),
          method: "POST",
          attr: { id: "createForm", class: "flex" }
        })
      }}
      {{ form_widget(createForm) }}
      <button type="submit" class="parameter_create">Créer un paramètre</button>
      {{ form_end(createForm) }}
  </div>
</section>
{% endblock %}

templates/parameter/edit_customer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Édition du client{% endblock %}

{% block body %}
    <h1>Édition du client</h1>

    {# Vérification de l'existence du client #}
    {% if form is not null %}
        {{ form_start(form) }}

        <div>
            {{ form_row(form.customerName) }}
        </div>

        <div>
            {{ form_row(form.customerEmail) }}
        </div>

        <div>
            {{ form_row(form.customerPhone) }}
        </div>

        <div>
            {{ form_row(form.customerAddressStreet) }}
        </div>

        <div>
            {{ form_row(form.customerAddressZipcode) }}
        </div>

        <div>
            {{ form_row(form.customerAddressCity) }}
        </div>

        <div>
            {{ form_row(form.customerAddressCountry) }}
        </div>

        <div>
            {{ form_row(form.customerVAT) }}
        </div>

        <div>
            {{ form_row(form.customerSIREN) }}
        </div>

        <div>
            {{ form_row(form.customerReference) }}
        </div>

        <div>
            {{ form_row(form.customerDateFrom) }}
        </div>

        <div>
            {{ form_row(form.customerDateTo) }}
        </div>

        <button type="submit">Enregistrer les modifications</button>

        {{ form_end(form) }}
    {% else %}
        <p>Client non trouvé.</p>
    {% endif %}
{% endblock %}

templates/parameter/projects.html.twig
{% extends 'base.html.twig' %}

{% block title %}Digi-3 - Gestion des projets{% endblock %}

{% block body %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('styles/parameter/projects.css') }}" async>
<style>
/* Style de la modal */
.modal {
    display: none; /* Par défaut la modal est cachée */
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.8); /* Fond sombre avec opacité plus forte */
    justify-content: center;
    align-items: center;
    z-index: 1000;
}

.modal-dialog {
    background-color: #333; /* Fond sombre pour la modal */
    color: white; /* Texte en blanc pour le contraste */
    padding: 20px;
    border-radius: 8px;
    width: 400px;
    text-align: center;
}

.modal-header {
    font-size: 20px;
    font-weight: bold;
    margin-bottom: 10px;
    color: #f1f1f1; /* Texte clair pour l'en-tête */
}

.modal-body {
    font-size: 16px;
    margin-bottom: 20px;
    color: #ccc; /* Texte plus clair dans le corps */
}

.modal-footer {
    display: flex;
    justify-content: center;
    gap: 15px;
}

.btn-cancel, .btn-delete {
    padding: 10px 20px;
    font-size: 16px;
    cursor: pointer;
    border-radius: 5px;
    border: none;
}

.btn-cancel {
    background-color: #f44336; /* Rouge pour annuler */
    color: white;
}

.btn-delete {
    background-color:rgb(181, 0, 0); /* Vert pour confirmer */
    color: white;
}

/* Style de la croix de fermeture */
.btn-close {
    background: transparent;
    border: none;
    font-size: 25px;
    color: #fff; /* Croix de fermeture en blanc */
    cursor: pointer;
    transition: color 0.3s ease, transform 0.3s ease; /* Transition fluide pour la couleur et la transformation */
}

/* Effet au survol de la croix de fermeture */
.btn-close:hover {
    color: #f44336; /* La croix devient rouge au survol */
    transform: scale(1.2); /* La croix devient légèrement plus grande */
}

.btn-close:focus {
    outline: none; /* Retirer l'outline lorsque la croix est cliquée */
}


</style>
{% endblock %}

{% include 'includes/header.html.twig' with {'user': user} %}

<section class="parameter_landing flex">
    {% include 'parameter/_menu.html.twig' %}
    <div class="parameter_content">
        <div class="projects-page">
            <div class="projects-header flex">
                <h2>Gestion des projets</h2>
            </div>

            {% for message in app.flashes('success') %}
                <div class="alert-success">{{ message }}</div>
            {% endfor %}
            {% for message in app.flashes('error') %}
                <div class="alert-error">{{ message }}</div>
            {% endfor %}

            <div class="projects-table">
                <table>
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Chef de projet</th>
                            <th>Description</th>
                            <th>Date début</th>
                            <th>Date fin Prévue</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <td>{{ project.name }}</td>
                                <td>
                                    {% if project.projectLeader %}
                                        {{ project.projectLeader.userFirstName }} {{ project.projectLeader.userLastName }}
                                    {% else %}
                                        Non défini
                                    {% endif %}
                                </td>
                                <td>{{ project.description }}</td> 
                                <td>{{ project.startDate ? project.startDate|date('d/m/Y') : '' }}</td>
                                <td>{{ project.endDateForecast ? project.endDateForecast|date('d/m/Y') : '' }}</td>
                                <td class="actions">
                                    <button class="btn-delete delete-project" 
                                            data-project-id="{{ project.id }}">
                                        <i class="fas fa-trash" style="font-size: 25px;" title="Supprimer"></i>
                                    </button>
                                </td>
                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="7" class="no-data">Aucun projet trouvé</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</section>

{# Delete Project Modal #}
<div class="modal" id="deleteProjectModal">
    <div class="modal-dialog">
        <div class="modal-header">
            <h3>Confirmer la suppression</h3>
            <button type="button" class="btn-close" onclick="closeModal()">×</button>
        </div>
        <div class="modal-body">
            <p>Êtes-vous sûr de vouloir supprimer ce projet ?</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn-cancel" onclick="closeModal()">Annuler</button>
            <button type="button" class="btn-delete" id="confirmDelete">Supprimer</button>
        </div>
    </div>
</div>

{% block javascripts %}
<script src="{{ asset('script/parameter/parameter.js') }}"></script>
<script>
    // Fonction pour ouvrir la modal
    function openModal(projectId) {
        const modal = document.getElementById('deleteProjectModal');
        const confirmButton = document.getElementById('confirmDelete');
        confirmButton.setAttribute('data-project-id', projectId);
        modal.style.display = 'flex'; // Afficher la modal
    }

    // Fonction pour fermer la modal
    function closeModal() {
        const modal = document.getElementById('deleteProjectModal');
        modal.style.display = 'none'; // Cacher la modal
    }

    // Ajouter l'événement de clic sur chaque bouton de suppression
    document.querySelectorAll('.delete-project').forEach(button => {
        button.addEventListener('click', function() {
            const projectId = this.getAttribute('data-project-id');
            openModal(projectId);
        });
    });

    // Gérer la confirmation de suppression
    document.getElementById('confirmDelete').addEventListener('click', function() {
        const projectId = this.getAttribute('data-project-id');
        
        if (projectId) {
            // Effectuer la suppression du projet via AJAX ou une autre méthode
            fetch('/parameter/projects/delete/' + projectId, {
                method: 'DELETE'
            })
            .then(response => {
                if (response.ok) {
                    // Fermer la modal et recharger la page ou mettre à jour la liste
                    closeModal();
                    window.location.reload(); // Ou vous pouvez retirer le projet de la table
                } else {
                    alert('Une erreur est survenue lors de la suppression du projet.');
                }
            });
        }
    });
</script>
{% endblock %}
{% endblock %}